### ISSUE TITLE
TypeError: window can't be nil for WX::Frame.new(nil) -- ruby-2.2.1, wxgtk3.0-dev

### ISSUE THREAD

**Issue by ptruog** [Hanmac/rwx#14]
[6] pry(main)> require 'rwx'
=> true
[7] pry(main)> 
[8] pry(main)> class App < WX::App
[8] pry(main)*   def on_init    
[8] pry(main)*     @frame = WX::Frame.new(nil)        
[8] pry(main)*     @button = WX::Button.new(@frame, label: 'test')        
[8] pry(main)*     
[8] pry(main)*     @frame.bind(:button_clicked) {}        
[8] pry(main)*     
[8] pry(main)*     
[8] pry(main)*     @frame.show        
[8] pry(main)*   end      
[8] pry(main)* end 
=> :on_init
[9] pry(main)> 
[10] pry(main)> App.new.main_loop
TypeError: window can't be nil.
from (pry):7:in `initialize'
[11] pry(main)> 

I built the gem via:
rake compile
rake package
gem install --local ./pkg/rwx-0.0.1.1.dev.gem

rake compile
cd ext
/usr/local/rvm/rubies/ruby-2.2.1/bin/ruby extconf.rb
checking for HAVE_RB_DATA_TYPE_T_PARENT... yes
checking for gcc... yes
checking for g++... yes
checking for HAVE_TYPE_TRAITS in wx/setup.h... no
checking for wx/preferences.h... no
checking for wxHAS_EVENT_BIND in wx/wx.h... yes
checking for wxContextHelpButton() in wx/cshelp.h... no
checking for wxNumberEntryDialog() in wx/numdlg.h... no
checking for wxPasswordEntryDialog() in wx/textdlg.h... no
checking for wxProgressDialog() in wx/progdlg.h... no
checking for wxMessageDialog() in wx/msgdlg.h... no
checking for wxGenericMessageDialog() in wx/wx.h,wx/generic/msgdlgg.h... no
checking for wxRichMessageDialog() in wx/richmsgdlg.h... no
checking for wxBusyInfoFlags() in wx/busyinfo.h... no
checking for wxFontPickerCtrl().GetSelectedColour() in wx/fontpicker.h... no
checking for wxInfoBar().GetButtonCount() in wx/infobar.h... no
checking for wxOwnerDrawnComboBox().IsListEmpty() in wx/odcombo.h... no
checking for wxFD_NO_FOLLOW in wx/filedlg.h... no
checking for wxDIRCTRL_DEFAULT_STYLE in wx/wx.h,wx/dirctrl.h... no
checking for wxDirCtrl() in wx/wx.h,wx/dirctrl.h... yes
checking for wxSTC_LEX_DMAP in wx/wx.h,wx/stc/stc.h... no
checking for wxSTC_LEX_TEHEX in wx/wx.h,wx/stc/stc.h... no
checking for wxStyledTextCtrl().GetTargetText() in wx/wx.h,wx/stc/stc.h... no
checking for wxStyledTextCtrl().IndicatorGetHoverStyle(0) in wx/wx.h,wx/stc/stc.h... no
checking for wxStyledTextCtrl().GetCaretLineVisibleAlways() in wx/wx.h,wx/stc/stc.h... no
checking for wxALIGN_CENTER_VERTICAL in wx/sizer.h... yes
checking for wxSizerFlags().CenterVertical() in wx/sizer.h... no
creating extconf.h
creating Makefile
make
linking shared-object rwx.so
cd ..

Sorry, I don't know how to break into the native library from ruby, where i'd love to break in here somewhere:
wxFrame.cpp:32
DLL_LOCAL VALUE _initialize(int argc,VALUE *argv,VALUE self)

**Comment by Hanmac** [comment]
should be fixed, there was a () missing while i did the style check
