### ISSUE TITLE
Errors when trying to install gem

### ISSUE THREAD

**Issue by developer1105** [Hanmac/rwx#19]
After running this command: ```gem install rwx --pre``` some error messages appear.
P.S: In C++ the 'hello world' example compiles and runs fine.
My distro is Arch Linux.
.
.
.
.

Building native extensions. This could take a while...
ERROR:  Error installing rwx:
	ERROR: Failed to build gem native extension.

    current directory: /home/myuser/.local/share/gem/ruby/3.0.0/gems/rwx-0.0.1.1.dev/ext
/usr/bin/ruby -I /usr/lib/ruby/3.0.0 extconf.rb
checking for wx-config... yes
checking for gcc... yes
checking for g++... yes
CC compiler missmatch /usr/bin/cc == gcc
CXX compiler missmatch /usr/bin/c++ == g++
checking for wx/preferences.h... yes
checking for wxHAS_EVENT_BIND in wx/wx.h... yes
checking for wxContextHelpButton() in wx/cshelp.h... yes
checking for wxNumberEntryDialog() in wx/numdlg.h... yes
checking for wxPasswordEntryDialog() in wx/textdlg.h... yes
checking for wxProgressDialog() in wx/progdlg.h... no
checking for wxMessageDialog() in wx/msgdlg.h... no
checking for wxGenericMessageDialog() in wx/generic/msgdlgg.h... no
checking for wxRichMessageDialog() in wx/richmsgdlg.h... no
checking for wxFontPickerCtrl().GetSelectedColour() in wx/fontpicker.h... yes
checking for wxInfoBar().GetButtonCount() in wx/infobar.h... yes
checking for wxOwnerDrawnComboBox().IsListEmpty() in wx/odcombo.h... yes
checking for wxFD_NO_FOLLOW in wx/filedlg.h... yes
checking for wxDIRCTRL_DEFAULT_STYLE in wx/wx.h,wx/dirctrl.h... yes
checking for wxDirCtrl() in wx/wx.h,wx/dirctrl.h... yes
checking for wxSTC_LEX_DMAP in wx/wx.h,wx/stc/stc.h... yes
creating extconf.h
creating Makefile

current directory: /home/myuser/.local/share/gem/ruby/3.0.0/gems/rwx-0.0.1.1.dev/ext
make DESTDIR\= sitearchdir\=./.gem.20231128-169537-vjqmuo sitelibdir\=./.gem.20231128-169537-vjqmuo clean

current directory: /home/myuser/.local/share/gem/ruby/3.0.0/gems/rwx-0.0.1.1.dev/ext
make DESTDIR\= sitearchdir\=./.gem.20231128-169537-vjqmuo sitelibdir\=./.gem.20231128-169537-vjqmuo
compiling main.cpp
g++: error: unrecognized command-line option '-pthread-I/usr/include/gtk-3.0'
g++: error: unrecognized command-line option '-pthread-I/usr/include/gtk-3.0'
make: *** [Makefile:238: main.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/myuser/.local/share/gem/ruby/3.0.0/gems/rwx-0.0.1.1.dev for inspection.
Results logged to /home/myuser/.local/share/gem/ruby/3.0.0/extensions/x86_64-linux/3.0.0/rwx-0.0.1.1.dev/gem_make.out

**Comment by Hanmac** [comment]
it has been very long since i worked on this, but it looks like there is a space missing "-pthread-I", but i don't know how

might be better if you checkout https://github.com/mcorino/wxRuby3 ?
