### ISSUE TITLE
Make rwx into a gem PLEASE :(

### ISSUE THREAD

**Issue by ghost** [Hanmac/rwx#3]
<Hanmac> i will gem it when i have the time for that :/
<shevy> haha
<shevy> ;)
<shevy> gem install rwx
<shevy> ERROR:  Could not find a valid gem 'rwx' (>= 0) in any repository
<shevy> ^^^ bug°

Filed a bug now. :)

**Comment by dapicester** [comment]
Sorry, not available yet:
```shell
$ gem install rwx
ERROR:  Could not find a valid gem 'rwx' (>= 0) in any repository
$ gem sources
*** CURRENT SOURCES ***

http://rubygems.org
````

**Comment by Hanmac** [comment]
@dapicester : it does have a dev version:
```gem install rwx --pre```
but that one is outdated and you should build it from source (i need to work on that again if i have time)

**Comment by dapicester** [comment]
@Hanmac OK, I will try to build it from source
