### ISSUE TITLE
HOW

### ISSUE THREAD

**Issue by zhimin** [Hanmac/rwx#5]
Hi, I generated the rwx-0.0.1.dev.gem   (Ruby 2.1, Wx 3.0 stable on Mac 10.8) 

 > rake compile gem

Trying to run the exmaple
 
 > cd samples/dialog; ruby dialog_sample.rb

The process seem hangs, Ctrl +C couldn't stop the process. 

Did I miss a step or something?   Thanks.

Regards,
Zhimin

**Comment by rinkevichjm** [comment]
you can close my issue as they build with more recent versions
